version: "2"

run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck

issues:
  exclude-dirs:
    - test
  exclude-files:
    - ".*_test\\.go$"
